//! @yah:ticket(R748-T5, "Publish readiness: mirror, publish = true, and an honest README")
//! @yah:status(review)
//! @yah:at(2026-08-12T01:18:36Z)
//! @yah:next("Both gates are now met (F1: chain landed + A/B/C verified; T3: 20 tests, invariant_a..g greppable) and the reclamation-zero gotcha is cleared: F2 landed and the kamaji-copy demo reclaimed 3 surplus sessions / 44 MB real (du) - 24% of that incremental tree - in one sweep at zero rebuild cost, with the edit loop at 0.95s after. README rewritten to lead with the gap (bins + incremental are refused by compiler caches and governed by nothing); Cargo.toml carries full publish metadata (license MIT, repository, keywords, categories). What remains is the operator-facing release sequence, in order: (1) gh repo create yah-ai/cargo-orphan-gc --public, (2) scripts/export-oss.sh orphan-gc [check the script knows this subtree - it is newer than the script's repo list], (3) flip publish = false to true, (4) cargo publish. Steps 1/2/4 are outward-facing; do not take them without operator confirmation.")
//! @yah:assignee(agent:bundle-anthropic-ashguard)
//! @yah:parent(R748)
//! @yah:next("Last, and gated on -F1 (it does not work alongside sccache yet) and -T3 (unproven deletion authority). Mechanics: Cargo.toml still carries publish = false and version 0.1.0; the crates.io name cargo-orphan-gc is unregistered (404, sanity-checked against cargo-sweep 200). oss/orphan-gc has no GitHub mirror, so its first scripts/export-oss.sh run needs `gh repo create yah-ai/cargo-orphan-gc --public` first — same first-time-export path srcgraph took. Follow the oss/ rule in CLAUDE.md: the monorepo is source of truth, changes flow outward through export-oss.sh, never edit the mirror.\n\nThe README should lead with the gap rather than the mechanism: cargo has no target-dir GC; sccache and friends cache what they can, and structurally REFUSE --crate-type bin and -C incremental; those refusals are the largest artifacts in a working target dir. State the safety invariants and their cost plainly, including that orphan-only mode cannot enforce a ceiling and that budget mode trades Invariant A for one.")
//! @yah:gotcha("Do not publish while the measured reclamation on realistic workloads is zero. Four scenarios today returned 0 bytes, and -F2 is the ticket that changes that. A GC tool whose headline number is 0 will be judged on that number, and the second impression is much more expensive than the first.")
//! @yah:depends_on(R748-F1)
//! @yah:depends_on(R748-T3)
//! @yah:handoff("Publish readiness done up to the four outward-facing steps, now listed in order in the publish comment in oss/orphan-gc/Cargo.toml.")
//! @yah:handoff("README leads with the gap and documents scripts/adoption-demo.sh with the measured reclamation (182 to 138 MB, 24 percent of the incremental tree, zero rebuild cost).")
//! @yah:handoff("export-oss.sh now knows this subtree: ALL_REPOS gained orphan-gc, plus a mirror_repo() mapping because the mirror is cargo-orphan-gc while the dir is orphan-gc.")
//! @yah:next("Operator: gh repo create yah-ai/cargo-orphan-gc --public, then scripts/export-oss.sh orphan-gc, then flip publish to true, then DRY_RUN=1 scripts/oss-publish.sh oss/orphan-gc and the real run.")
//! @yah:verify("20 tests pass on stable and on 1.85.0; cargo clippy --all-targets is silent; a clean-target-dir build emits zero warnings.")
//! @yah:verify("cargo package --allow-dirty packages 25 files / 186.5 KiB and its verification build succeeds.")
//! @yah:verify("crates.io cargo-orphan-gc is 404 as of 2026-08-11, sanity-checked against cargo-sweep 200 - send a User-Agent, a bare curl gets 403 for both and every name looks free.")
//! @yah:gotcha("`cargo package` poisons this crate's build until you notice. Its verification build unpacks to target/package/cargo-orphan-gc-<version>/, which has no target dir of its own, so it writes the BIN unit's fingerprint into target/debug/.fingerprint with a dep-info naming the unpacked copy's sources. Those never change again, so cargo reports 'Fresh' forever and target/debug/cargo-orphan-gc silently stays frozen at the packaged revision - while cargo test keeps rebuilding (different unit hash) and looks like proof the binary is current. Found 2026-08-12 with the binary a day stale; every manual CLI check that morning was testing Aug-11 code. Always run `cargo package --allow-dirty --target-dir target/package-verify`; recover with `rm -rf target/debug/.fingerprint/cargo-orphan-gc-<binhash>`. Also recorded in the release comment in oss/orphan-gc/Cargo.toml.")
//!
//! @yah:ticket(R748-T11, "Deleting-mode soak: hold R748 open, collect what real use breaks, then cut 0.8")
//! @yah:at(2026-08-13T00:46:06Z)
//! @yah:status(open)
//! @yah:assignee(agent:bundle-anthropic-ashguard)
//! @yah:parent(R748)
//! @yah:next("Operator decision 2026-08-12: do NOT archive R748 while this is open. This ticket exists so the relay stays alive as the holding place for orphan-gc findings - a relay derives its column from its children, and every other R748 child is in review, so without this one R748 reads as finished and board hygiene would archive it. R748 is the ONLY relay holding orphan-gc: verified against board inflight, the adjacent ones (R709 camp janitor scheduled sweep, R744 Rust stack profile) are neighbours, not owners.")
//! @yah:verify("File bugs found in real use as R748 children, not here. This ticket is the holder; it closes when 0.8 ships.")
//! @yah:next("The soak that earns the release: the camp went to dry-run = false on 2026-08-12 with 58 families / 42.0 GB tracked, so this is the first period where the tool actually deletes on a shared tree under ten concurrent agents. What to watch: (a) any build failing with `extern location for <crate> does not exist` - that is B9's shape returning and means enabled = false immediately; (b) `cargo orphan-gc log` under $CARGO_HOME/orphan-gc/workspaces/<hash>/ for deletions that do not correspond to a real supersession; (c) whether orphan-only supersession ever reclaims a non-zero byte count, since it has measured exactly 0 at every scale so far and 100% of real value is F2's surplus-session collector; (d) the W306 contention number - per-member overhead at root-workspace scale under agent load, still unmeasured and still the open half of the adoption verdict.")
//! @yah:next("Release shape when the soak has earned it: the crate is version 0.1.0 today while every sibling under oss/ is 0.8.22, so a 0.8 cut is also a version alignment, not just a bump. R748-T5 (publish readiness - mirror, publish = true, honest README) is already in review and is the gate. Root CLAUDE.md carries the exact sequence: gh repo create yah-ai/cargo-orphan-gc --public, then scripts/export-oss.sh orphan-gc, then flip publish, then scripts/oss-publish.sh oss/orphan-gc. Note the mirror name differs from the directory name (cargo- plugin prefix); export-oss.sh knows the mapping in mirror_repo() and nothing else needs to.")
//! @yah:gotcha("Version alignment is a real decision, not a formality: publishing cargo-orphan-gc at 0.8.x claims a maturity the 0.1.0 in the manifest does not. It is defensible here because the whole oss/ tree moves in lockstep and a 0.1.0 sibling would be the odd one out - but say so in the README rather than letting the number imply a year of production use.")
//!
//! @yah:relay(R770, "cargo-orphan-gc races concurrent builds: deletes in-use build-script OUT_DIR contents, breaking libsqlite3-sys/tree-sitter mid-build")
//! @yah:at(2026-08-16T02:41:15Z)
//! @yah:assignee(agent:bundle-anthropic-miravel)
//! @yah:next("Reproduce with 2+ concurrent `cargo build` invocations in this repo (shared target dir) and watch whether cargo-orphan-gc's sweep deletes an OUT_DIR still owned by an in-flight rustc/build-script process.")
//! @yah:next("Check whatever liveness/lock check oss/orphan-gc uses before deleting a build-script out/ dir -- it's apparently not seeing the concurrent build as active.")
//! @yah:gotcha("Hit 4x in ~40min while rebuilding for R768 in a busy camp (3+ concurrent cargo builds): `error: couldn't read target/release-dev/build/{libsqlite3-sys,tree-sitter}-<hash>/out/{bindgen.rs,stdlib-symbols.txt}: No such file or directory`. The build dir's `output`/fingerprint files are intact -- only the generated file(s) inside out/ are gone, and it recurs on a DIFFERENT crate's build dir each retry after `rm -rf`'ing the previous one. `.cargo/config.toml` sets `rustc-wrapper = \"cargo-orphan-gc\"` globally (every rustc invocation, including concurrent builds from other live camp sessions, runs through it) -- the pattern (fingerprint intact, only out/ payload missing, moves to whichever crate is mid-build next) looks like it's classifying an in-use OUT_DIR as orphaned and deleting its contents while a sibling rustc process still needs it.")
//! @yah:handoff("MITIGATED 2026-08-15 (@Miravel:eclipse, chat session): flipped root Cargo.toml `[workspace.metadata.orphan-gc]` back to `dry-run = true` (was `false` since 2026-08-12) -- stops live deletion camp-wide while this is open. Also added a loud top-of-file warning to root CLAUDE.md telling agents to suspect orphan-gc first on any build error that looks like a compiler bug (missing generated file, wrong crate, non-reproducible). Re-enable `dry-run = false` only after the liveness-check fix here is verified against a real concurrent-build repro.")
//! @yah:gotcha("Second victim shape found independently the same session (chat, session:4812f867): `libyah_qed_gha-d286424a3d4d8fa6.rmeta` and `libyah_hetzner-ee7bd60615e1ff2b.rmeta` both missing from target/release-dev/deps while their matching `.rlib` and `.d` files (same hash) are intact -- same 'fingerprint/companion file intact, one generated payload gone' signature as the OUT_DIR case, on crates reached via [patch.crates-io] into oss/qed and oss/yubaba (cross-workspace path deps, same shape R742-F1 originally flagged). No orphan-gc process or cron/launchd job was live at inspection time, so this is a race window during an earlier build, not a standing process still deleting.")
//! @yah:handoff("FIX APPLIED 2026-08-15 (@Miravel:eclipse, chat session, not yet committed): gc.rs::sweep_pending now logs per-family when policy.verbose and (deleted>0 or deferred>0) -- 'background sweep of pending family <label>: ...', same shape as the per-compile line. `cargo check` and `cargo test` run clean in oss/orphan-gc. This closes the observability gap (every deletion is now attributable) but does NOT fix the underlying race -- it makes the NEXT occurrence traceable to a specific family + timestamp, which R770's actual fix needs. Left dry-run=false per operator direction (2026-08-15 correction to my own earlier shadow-mode backout): the camp needs real reclamation, the responsibility is attribution before any clean+rebuild, not disabling deletion. Root CLAUDE.md now documents that triage protocol at the top of the file.")
//! @yah:gotcha("ROOT-CAUSE LEAD for the rmeta/rlib shape (not yet fully proven end-to-end, but code-confirmed): `cargo orphan-gc log` for the whole day (05:45Z-00:40Z, ~8600 lines, no rotation) has ZERO nonzero-deletion entries for yah_qed_gha or yah_hetzner -- their own compiles never logged deleting anything. That rules OUT the main, logged sweep path (wrapper.rs run_in -> gc::sweep_locked, logged at wrapper.rs:184-205). But wrapper.rs:210-219 also runs `gc::sweep_pending` (up to `pending-sweeps-per-compile` = 4 OTHER pending families) on EVERY successful compile, and its report was silently discarded (`let _ = gc::sweep_pending(...)`) -- a background deletion path with NO log line at all, unattributable by construction. That is almost certainly the actual mechanism: some unrelated crate's compile triggers a background sweep that reaps a DIFFERENT family's orphaned generation, invisible in the operational log.")
//! @yah:gotcha("LIKELY MISDIAGNOSIS on the original OUT_DIR claim (libsqlite3-sys/tree-sitter bindgen.rs/stdlib-symbols.txt). R748-B12 (status: review) diagnosed and fixed this EXACT shape as camp_service::sweep's mtime-cutoff walk into build/*/out/ -- unrelated to orphan-gc entirely -- and its own gotchas explicitly say 'NOT cargo-orphan-gc... Do not re-diagnose this as an orphan-gc bug' and record that R742-F3 already filed and retracted this identical misattribution. R748-B12's fix is in source but NOT yet in the long-lived camp-service daemons doing the deleting (spawn_disk_sweep, restart-only), so the symptom will keep recurring every ~30min independent of anything done here until those restart -- that alone explains repeat hits without invoking orphan-gc at all. Do not cite the OUT_DIR gotchas above as orphan-gc evidence; see R748-B12 instead. The deps/ rmeta+rlib+d finding (yah_qed_gha/yah_hetzner) is NOT covered by R748-B12's fix (which only excludes build/ and incremental/, deps/ is still actively swept by both camp_service AND orphan-gc) and remains the one still-open, not-yet-attributed lead for THIS ticket -- both share the same underlying anti-pattern: a sweep deleting one file out of a set (OUT_DIR payload, or {rmeta,rlib,d}) that is only valid as a whole.")
//! @yah:handoff("cargo-orphan-gc REINSTALLED 2026-08-15 (@Miravel:eclipse) with the sweep_pending logging fix: `cd oss/orphan-gc && cargo install --path . --force`, replaced ~/.cargo/bin/cargo-orphan-gc in place (same path, does not invalidate fingerprints per the R748-B9 handoff precedent). Unblocked the build with `cargo clean -p bash-ast -p cheers-server -p mesofact-publisher --profile release-dev`. From here forward, ANY deletion via either path logs its family -- the next hit should finally be attributable. If it recurs with a clean attribution to orphan-gc's own sweep (main or background), that confirms the mechanism; if it recurs with STILL no log entry, orphan-gc is cleared and the deps/ hazard is a third, undiagnosed source.")
//! @yah:gotcha("THIRD OCCURRENCE, same session, fresh enough to bound tightly: bash_ast/cheers_server/mesofact_publisher rmeta all missing while rlib+d survive, hashes 4f192993725c0733/678e80695482bd7c/b5f8ec5ff8bca90e. rlib write times (local) 18:05-18:08, discovered missing by 18:14 -- a 6-9 MINUTE window, not hours. Checked orphan-gc log at each crate's own write-time compile: all show deleted=0/deferred=0 (only session collection), so once again the pre-fix binary's silent sweep_pending path is the only candidate; no smoking gun possible from the old log by construction. Separately noticed while reading the tail: `tracked live+orphan bytes` is 1.7-1.8 TB against a 150 GiB max-bytes ceiling (11x over) on EVERY compile right now, and budget-mode is still the orphan-only default so nothing acts on it -- worth its own look, not chased further here.")
//! @yah:handoff("GRACE-PERIOD FIX landed and installed (@Miravel:dove, relay session). Root cause for the rmeta/rlib shape, confirmed by code reading independent of the peer chat session's parallel work: Lease (lease.rs) only protects the --extern inputs of a rustc invocation that is CURRENTLY RUNNING -- it has zero visibility into cargo's build plan, so a unit that will need a given generation's artifact as --extern but hasn't started its own rustc invocation yet is invisible to lease::active_inputs. sweep_pending's cross-family background retries (the silent path the peer's earlier logging fix now instruments) can therefore reach a generation minutes before the downstream unit that still needs it has even started.")
//! @yah:handoff("Fix: state.rs Generation gained orphaned_unix_ms (Option<u128>, stamped at the moment a generation is pushed into orphans -- wrapper.rs's own-compile supersession, and gc.rs budget_sweep retirement). gc.rs sweep_locked_protecting now defers a WHOLE generation (same deferred_artifacts bucket as an active-lease hit) until now_ms() - orphaned_unix_ms >= policy.orphan_grace_ms, a new config.rs Policy field defaulting to 30 minutes -- comfortably past the 6-9 minute vanish window measured live in this same session (bash_ast/cheers_server/mesofact_publisher, hashes 4f192993725c0733/678e80695482bd7c/b5f8ec5ff8bca90e). Budget-mode retirement is deliberately EXEMPT (stamped Some(0), pre-aged): it sweeps synchronously under the same lock it just retired under, re-checking leases fresh -- no cross-invocation timing gap exists there, and graceing it would defeat the ceiling's whole purpose.")
//! @yah:handoff("This narrows the race, it does not close it -- a downstream unit that cargo doesn't schedule within 30 minutes (heavy contention, a stalled build) is still exposed. Documented at the Policy::orphan_grace_ms doc comment.")
//! @yah:handoff("Tests: new gc::tests::a_generation_orphaned_within_the_grace_period_is_deferred_whole pins both halves (fresh orphan defers whole, same fixture aged past the grace period sweeps normally). All 6 existing Generation-literal fixtures across gc.rs/wrapper.rs updated for the new field; wrapper.rs's own fixture() sets orphan_grace_ms = 0 since those invariant tests supersede-then-sweep synchronously in one test body and were never about this race. 45 tests total (was 43), clippy --all-targets silent.")
//! @yah:handoff("Binary rebuilt (cargo build --release) and reinstalled (cargo install --path . --force) over the peer's earlier sweep_pending-logging install, same path, same no-fingerprint-invalidation precedent. Verified live: cargo check -p yah --lib now exits 0 (was failing with the 3-crate extern-location error at session start) and all three previously-missing .rmeta files are back on disk.")
//! @yah:handoff("OUT_DIR misdiagnosis: independently reached the same conclusion the peer chat session (@Miravel:eclipse) already recorded in source -- artifacts::collect only walks out_dir's DIRECT children (fs::read_dir, non-recursive) and no Invocation ever sets out_dir to a build-script's out/ subdirectory (that path is only ever exposed to the build-script BINARY at execution time via an env var, never to any rustc argv orphan-gc parses; build-script execution itself is not an rustc invocation and is never wrapped at all). The bindgen.rs/stdlib-symbols.txt shape structurally cannot be orphan-gc's OwnedArtifact tracking; see R748-B12 in the source annotations for the actual (already-fixed-in-source, not-yet-deployed) camp_service::sweep cause.")
//! @yah:handoff("Filed R748-B13 (parent R748, not this ticket) for the separate, not-chased tracked-bytes-vs-max-bytes overage the peer noticed in passing (1.7-1.8 TB against a 150 GiB ceiling with budget-mode still orphan-only) -- unrelated subsystem, needs its own investigation into whether the figure is real or a size_identity dedup gap at a third site.")
//! @yah:handoff("Tree anchor at handoff: 5f2ad531f17f3387b1bf46d9a28c4dd5a986b6dc — the shared tree as I left it. Diff against it (`git diff 5f2ad531f17f3387b1bf46d9a28c4dd5a986b6dc..HEAD`) to see what landed under you, and quote this SHA rather than 'HEAD' in any revert/restore instruction.")
//! @yah:next("Watch `cargo orphan-gc log` over the camp's continued build activity for any further rmeta/rlib vanish: with the grace period AND the per-family sweep_pending logging both live now, a recurrence will name the family, the timestamp, and show whether it happened despite the grace window (which would mean the mitigation is insufficient, not just unverified) or reveal a fourth, still-undiagnosed mechanism.")
//! @yah:next("If the grace period holds for a day of real camp load with zero unattributed vanishes, that is the closest this ticket can get to the 'reproduce with 2+ concurrent cargo build invocations' ask without a synthetic harness -- worth a deliberate synthetic repro (two concurrent `cargo build` processes racing the same target dir on a crate with a long build-script) only if a live recurrence still happens with the grace period in place.")
//! @yah:next("Re-enable consideration for dry-run stays false per operator direction (2026-08-15) -- no change needed there, already correct on disk.")
//! @yah:handoff("VERIFIED 2026-08-16T02:4x (@Miravel:polaris, continuation session, no code changes): grace-period fix intact and installed. oss/orphan-gc test suite 45/45 pass, `cargo clippy --all-targets` silent. `cargo orphan-gc status` confirms the installed binary (mtime 2026-08-16T01:24:07Z) is live: enabled=true, mode=deleting (dry-run=false). Root Cargo.toml [workspace.metadata.orphan-gc] dry-run=false reconfirmed correct per 2026-08-15 operator direction -- no drift.")
//! @yah:handoff("Inspected the orphan-gc log for the ~70min window since binary install (2026-08-16T01:24:07Z-02:35:44Z) during genuine concurrent camp build load (9+ distinct pids compiling simultaneously per the log's own pid= field). Every deletion in that window carries a family-attributed log line (own-compile or 'background sweep of pending family ...'), and the grace-period defer path is visibly firing live, e.g. 'cheers_core: deleted 58 artifacts, deferred 62' the same second as its background-sweep siblings deferring cleanly. Zero unattributed vanishes, zero recurrence of the original missing-generated-file error class in this window.")
//! @yah:handoff("Tree anchor at handoff: b2157985a18b0046529cd1e15fd0787caf10ea47 — the shared tree as I left it. Diff against it (`git diff b2157985a18b0046529cd1e15fd0787caf10ea47..HEAD`) to see what landed under you, and quote this SHA rather than 'HEAD' in any revert/restore instruction.")
//! @yah:next("Continue watching `cargo orphan-gc log` across further real camp load for any unattributed vanish (grep for 'deleted' lines with no preceding family attribution, or a fresh 'does not exist'/'No such file or directory' build error). ~70min clean is encouraging but well short of the 'day of real load' bar the grace-period fix needs before it's trustworthy.")
//! @yah:next("A synthetic 2+-concurrent-cargo-build repro remains un-built and is still only worth constructing if a live recurrence happens despite the grace period (per prior session's own gate) -- it hasn't, so don't build it speculatively; next session should re-check the log first.")
//! @yah:next("dry-run stays false per 2026-08-15 operator direction -- confirmed still correctly set, no action needed unless a new recurrence changes the calculus.")
//! @yah:gotcha("2026-08-16 R737-F2 (session:b2c3a2ad/dragon): cargo test -p yubaba in oss/yubaba (separate workspace, own target dir) failed with \"couldn't read .../build/libsqlite3-sys-1aae160415cd8d06/out/bindgen.rs: No such file or directory\" while ~5 concurrent camp builds were running (R605-F3, R764, R776, R775, R767, R752 all active per camp.roster). cargo orphan-gc log -n 5000 had NO entry naming bindgen, sqlite, or either build hash (1aae160415cd8d06 / aaf928902899d401) in the retained window -- inconclusive, not confirmed as this tool's doing. Filesystem evidence was consistent with the described bug though: the stale build dir's out/ still had libsqlite3.a + the .o but bindgen.rs specifically was gone, and a second, newer libsqlite3-sys hash dir existed with no out/ at all (never completed). Recovery: removed only the two libsqlite3-sys build dirs plus their 3 matching .fingerprint/ entries (not a full clean); cargo check -p yubaba then succeeded. Worth checking whether the log's family-keyed scheme even captures build-script OUT_DIR deletions by name at all -- if not, grepping the log for a missing generated file will always come up empty regardless of root cause.")
//! @yah:gotcha("OCCURRENCE 2026-08-19 that ORPHAN-GC DID NOT CAUSE (R783-F1 session, @Ashguard:griffin) - recorded because a negative is evidence too. Textbook symptom: cargo run -p xtask -- emit-schemas died with 'extern location for yah_plugin does not exist: target/debug/deps/libyah_plugin-30ce9c8a10d78148.rmeta' on a crate the session never touched. Ran the CLAUDE.md protocol before cleaning. cargo orphan-gc log -n 3000 (the whole retained window, back to 2026-08-19T01:34Z) contains ZERO deletions - every line is either 'deleted 0 artifacts (0 bytes), deferred N' or the max-bytes orphan-only-mode notice - and the hash 30ce9c8a10d78148 appears nowhere in it. On disk libyah_plugin-30ce9c8a10d78148.rlib and .d were BOTH PRESENT (Aug 19 02:04); only the .rmeta of that same hash was gone, with an older 027128d755190241.rmeta still there. So an rmeta/rlib pair can split without this tool touching it: the missing-rmeta signature is NOT sufficient to attribute an occurrence to orphan-gc, and a fix aimed only at concurrent deletion will not retire this class of failure. cargo clean -p yah-plugin plus rebuild cleared it.")
//! @yah:gotcha("OCCURRENCE 2026-08-20 ~07:10Z, with a NEW discriminator. cargo test -p desktop --lib died with 7 'extern location for X does not exist' errors naming libkg_store / libkg_ts / librunner / libkg / libparty rmetas, while compiling yah-eval, a crate the session never touched (R725-F1 was editing agent-tools + cli + desktop). THE TELL: target/debug/deps/libparty-c8870e3f71701ad8.rlib EXISTS and libparty-c8870e3f71701ad8.rmeta with THE SAME HASH does not. A peer rebuild replaces both halves under a NEW hash; a half-pair at ONE hash is a deletion of one file, which is exactly the rmeta/rlib-pair mode this ticket describes.")
//! @yah:gotcha("SAME OCCURRENCE, the part that should change how this is debugged: the tool's own log did NOT name it. cargo orphan-gc log -n 20000 reaches back to 2026-08-20T05:54Z and contains ZERO lines matching 'deleted [1-9]' - every entry is 'deleted 0 artifacts'. Yet several families in that same window report non-zero 'already gone' with no delete line anywhere for them (yah_plugin 123, yah_bundled 64, cloud_client 21). So step 1 of the CLAUDE.md protocol ('if this tool's own log names it, that is your root cause, confirmed') currently cannot confirm OR clear orphan-gc: a deleting path that does not log is indistinguishable from an innocent one. Making every unlink log is a prerequisite for attributing the next occurrence. Camp was at ~50 concurrent cargo processes.")

mod artifacts;
mod bootstrap;
mod cli;
mod config;
mod family;
mod gc;
mod lease;
mod log;
mod state;
mod wrapper;

use std::process;

use anyhow::{anyhow, Result};

fn main() {
    let code = match dispatch() {
        Ok(code) => code,
        Err(err) => {
            eprintln!("cargo-orphan-gc: {err:#}");
            2
        }
    };
    process::exit(code);
}

fn dispatch() -> Result<i32> {
    let mut args = std::env::args_os();
    let _exe = args.next();
    let first = args
        .next()
        .ok_or_else(|| anyhow!("expected Cargo subcommand invocation or rustc wrapper invocation"))?;

    // Cargo custom subcommands are invoked as:
    //   cargo-orphan-gc orphan-gc <args...>
    // Cargo rustc wrappers are invoked as:
    //   cargo-orphan-gc <path-to-real-rustc> <rustc-args...>
    if first == *"orphan-gc" {
        cli::run(args.collect())?;
        Ok(0)
    } else {
        wrapper::run(first, args.collect())
    }
}
